-- EduCri schema with roles: profesor / moderador
-- Execute in Supabase SQL Editor.

-- ---------------------------------------------------------------------------
-- Helper role check from JWT metadata
-- ---------------------------------------------------------------------------
create or replace function public.is_moderator()
returns boolean
language sql
stable
as $$
    select coalesce((auth.jwt() -> 'user_metadata' ->> 'role') = 'moderador', false)
        or coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'moderador', false);
$$;

-- ---------------------------------------------------------------------------
-- Classes
-- ---------------------------------------------------------------------------
create table if not exists public.classes (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    category text not null default 'otros',
    teacher text not null,
    classroom text not null,
    day text not null,
    time text not null,
    description text null,
    pdf_name text null default 'temario.pdf',
    color text null default 'from-blue-500 to-cyan-400',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    updated_by uuid null references auth.users(id) on delete set null
);
alter table public.classes
    add column if not exists updated_at timestamptz not null default now(),
    add column if not exists updated_by uuid null references auth.users(id) on delete set null,
    add column if not exists pdf_url text null;

create index if not exists classes_user_id_idx on public.classes(user_id);
alter table public.classes enable row level security;
alter table public.classes
    drop constraint if exists classes_day_valid,
    drop constraint if exists classes_time_valid;
alter table public.classes
    add constraint classes_day_valid check (day in ('Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo')),
    add constraint classes_time_valid check (time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$');

drop policy if exists "classes_select_own_or_moderator" on public.classes;
create policy "classes_select_own_or_moderator"
on public.classes
for select
to authenticated
using (auth.uid() = user_id or public.is_moderator());

drop policy if exists "classes_insert_own_or_moderator" on public.classes;
create policy "classes_insert_own_or_moderator"
on public.classes
for insert
to authenticated
with check (auth.uid() = user_id or public.is_moderator());

drop policy if exists "classes_update_own_or_moderator" on public.classes;
create policy "classes_update_own_or_moderator"
on public.classes
for update
to authenticated
using (auth.uid() = user_id or public.is_moderator())
with check (auth.uid() = user_id or public.is_moderator());

drop policy if exists "classes_delete_own_or_moderator" on public.classes;
create policy "classes_delete_own_or_moderator"
on public.classes
for delete
to authenticated
using (auth.uid() = user_id or public.is_moderator());

-- ---------------------------------------------------------------------------
-- Teacher profiles and validation status
-- ---------------------------------------------------------------------------
create table if not exists public.teacher_profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null default '',
    birth_date date null,
    phone text null,
    has_cds boolean not null default false,
    received_holy_spirit boolean not null default false,
    teaching_experience text not null default '',
    approval_status text not null default 'pending'
        check (approval_status in ('pending', 'approved', 'rejected')),
    approved_by uuid null references auth.users(id) on delete set null,
    approved_at timestamptz null,
    approval_notes text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    updated_by uuid null references auth.users(id) on delete set null
);
alter table public.teacher_profiles
    add column if not exists updated_at timestamptz not null default now(),
    add column if not exists updated_by uuid null references auth.users(id) on delete set null;

create index if not exists teacher_profiles_status_idx on public.teacher_profiles(approval_status);
create index if not exists teacher_profiles_approved_by_idx on public.teacher_profiles(approved_by);
alter table public.teacher_profiles enable row level security;

drop policy if exists "teacher_profiles_select_own_or_moderator" on public.teacher_profiles;
create policy "teacher_profiles_select_own_or_moderator"
on public.teacher_profiles
for select
to authenticated
using (auth.uid() = user_id or public.is_moderator());

drop policy if exists "teacher_profiles_insert_own_or_moderator" on public.teacher_profiles;
create policy "teacher_profiles_insert_own_or_moderator"
on public.teacher_profiles
for insert
to authenticated
with check (auth.uid() = user_id or public.is_moderator());

drop policy if exists "teacher_profiles_update_own_or_moderator" on public.teacher_profiles;
create policy "teacher_profiles_update_own_or_moderator"
on public.teacher_profiles
for update
to authenticated
using (auth.uid() = user_id or public.is_moderator())
with check (auth.uid() = user_id or public.is_moderator());

-- ---------------------------------------------------------------------------
-- Students assigned to class/teacher
-- ---------------------------------------------------------------------------
create table if not exists public.students (
    id bigint generated by default as identity primary key,
    full_name text not null,
    class_category text not null
        check (class_category in ('corderitos', 'soldaditos', 'vencedores', 'otros')),
    teacher_id uuid null references auth.users(id) on delete set null,
    created_by uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    updated_by uuid null references auth.users(id) on delete set null,
    deleted_at timestamptz null,
    deleted_by uuid null references auth.users(id) on delete set null
);
alter table public.students
    add column if not exists updated_at timestamptz not null default now(),
    add column if not exists updated_by uuid null references auth.users(id) on delete set null,
    add column if not exists deleted_at timestamptz null,
    add column if not exists deleted_by uuid null references auth.users(id) on delete set null;

create index if not exists students_teacher_id_idx on public.students(teacher_id);
create index if not exists students_class_category_idx on public.students(class_category);
alter table public.students enable row level security;

drop policy if exists "students_select_assigned_or_moderator" on public.students;
create policy "students_select_assigned_or_moderator"
on public.students
for select
to authenticated
using (public.is_moderator() or (teacher_id = auth.uid() and deleted_at is null));

drop policy if exists "students_insert_moderator_only" on public.students;
create policy "students_insert_moderator_only"
on public.students
for insert
to authenticated
with check (public.is_moderator() and created_by = auth.uid());

drop policy if exists "students_update_moderator_only" on public.students;
create policy "students_update_moderator_only"
on public.students
for update
to authenticated
using (public.is_moderator())
with check (public.is_moderator());

drop policy if exists "students_delete_moderator_only" on public.students;
create policy "students_delete_moderator_only"
on public.students
for delete
to authenticated
using (public.is_moderator());

-- ---------------------------------------------------------------------------
-- Tasks assigned by moderator to teachers
-- ---------------------------------------------------------------------------
create table if not exists public.teacher_tasks (
    id bigint generated by default as identity primary key,
    teacher_id uuid not null references auth.users(id) on delete cascade,
    class_category text not null
        check (class_category in ('corderitos', 'soldaditos', 'vencedores', 'otros')),
    title text not null,
    notes text null,
    day text not null,
    time text not null,
    assigned_by uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    updated_by uuid null references auth.users(id) on delete set null,
    deleted_at timestamptz null,
    deleted_by uuid null references auth.users(id) on delete set null
);
alter table public.teacher_tasks
    add column if not exists updated_at timestamptz not null default now(),
    add column if not exists updated_by uuid null references auth.users(id) on delete set null,
    add column if not exists deleted_at timestamptz null,
    add column if not exists deleted_by uuid null references auth.users(id) on delete set null;

create index if not exists teacher_tasks_teacher_id_idx on public.teacher_tasks(teacher_id);
create index if not exists teacher_tasks_assigned_by_idx on public.teacher_tasks(assigned_by);
alter table public.teacher_tasks enable row level security;
alter table public.teacher_tasks
    drop constraint if exists teacher_tasks_day_valid,
    drop constraint if exists teacher_tasks_time_valid;
alter table public.teacher_tasks
    add constraint teacher_tasks_day_valid check (day in ('Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo')),
    add constraint teacher_tasks_time_valid check (time ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$');

drop policy if exists "teacher_tasks_select_assigned_or_moderator" on public.teacher_tasks;
create policy "teacher_tasks_select_assigned_or_moderator"
on public.teacher_tasks
for select
to authenticated
using (public.is_moderator() or (teacher_id = auth.uid() and deleted_at is null));

drop policy if exists "teacher_tasks_insert_moderator_only" on public.teacher_tasks;
create policy "teacher_tasks_insert_moderator_only"
on public.teacher_tasks
for insert
to authenticated
with check (public.is_moderator() and assigned_by = auth.uid());

drop policy if exists "teacher_tasks_update_moderator_only" on public.teacher_tasks;
create policy "teacher_tasks_update_moderator_only"
on public.teacher_tasks
for update
to authenticated
using (public.is_moderator())
with check (public.is_moderator());

drop policy if exists "teacher_tasks_delete_moderator_only" on public.teacher_tasks;
create policy "teacher_tasks_delete_moderator_only"
on public.teacher_tasks
for delete
to authenticated
using (public.is_moderator());

-- ---------------------------------------------------------------------------
-- Attendance records by teacher
-- ---------------------------------------------------------------------------
create table if not exists public.attendance_records (
    id bigint generated by default as identity primary key,
    teacher_id uuid not null references auth.users(id) on delete cascade,
    student_id bigint not null references public.students(id) on delete cascade,
    class_id bigint null references public.classes(id) on delete set null,
    attendance_date date not null,
    status text not null check (status in ('present', 'absent', 'late')),
    note text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    updated_by uuid null references auth.users(id) on delete set null,
    unique (teacher_id, student_id, attendance_date)
);
alter table public.attendance_records
    add column if not exists updated_at timestamptz not null default now(),
    add column if not exists updated_by uuid null references auth.users(id) on delete set null;

create index if not exists attendance_records_teacher_date_idx on public.attendance_records(teacher_id, attendance_date);
create index if not exists attendance_records_student_idx on public.attendance_records(student_id);
alter table public.attendance_records enable row level security;

drop policy if exists "attendance_select_own_or_moderator" on public.attendance_records;
create policy "attendance_select_own_or_moderator"
on public.attendance_records
for select
to authenticated
using (public.is_moderator() or teacher_id = auth.uid());

drop policy if exists "attendance_insert_own_or_moderator" on public.attendance_records;
create policy "attendance_insert_own_or_moderator"
on public.attendance_records
for insert
to authenticated
with check (public.is_moderator() or teacher_id = auth.uid());

drop policy if exists "attendance_update_own_or_moderator" on public.attendance_records;
create policy "attendance_update_own_or_moderator"
on public.attendance_records
for update
to authenticated
using (public.is_moderator() or teacher_id = auth.uid())
with check (public.is_moderator() or teacher_id = auth.uid());

drop policy if exists "attendance_delete_moderator_only" on public.attendance_records;
create policy "attendance_delete_moderator_only"
on public.attendance_records
for delete
to authenticated
using (public.is_moderator());

-- ---------------------------------------------------------------------------
-- Trigger to auto-create teacher profile on signup
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user_teacher_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.teacher_profiles (
        user_id,
        full_name,
        birth_date,
        phone,
        has_cds,
        received_holy_spirit,
        teaching_experience,
        approval_status
    )
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        nullif(new.raw_user_meta_data ->> 'birth_date', '')::date,
        nullif(new.raw_user_meta_data ->> 'phone', ''),
        coalesce((new.raw_user_meta_data ->> 'has_cds')::boolean, false),
        coalesce((new.raw_user_meta_data ->> 'received_holy_spirit')::boolean, false),
        coalesce(new.raw_user_meta_data ->> 'teaching_experience', ''),
        case
            when coalesce(new.raw_user_meta_data ->> 'role', 'profesor') = 'moderador' then 'approved'
            else 'pending'
        end
    )
    on conflict (user_id) do update
    set
        full_name = excluded.full_name,
        birth_date = excluded.birth_date,
        phone = excluded.phone,
        has_cds = excluded.has_cds,
        received_holy_spirit = excluded.received_holy_spirit,
        teaching_experience = excluded.teaching_experience,
        updated_at = now();

    return new;
end;
$$;

drop trigger if exists on_auth_user_created_teacher_profile on auth.users;
create trigger on_auth_user_created_teacher_profile
after insert on auth.users
for each row execute function public.handle_new_user_teacher_profile();

-- ---------------------------------------------------------------------------
-- Audit triggers
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_fields()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    new.updated_by = auth.uid();
    return new;
end;
$$;

drop trigger if exists classes_set_updated_fields on public.classes;
create trigger classes_set_updated_fields
before update on public.classes
for each row execute function public.set_updated_fields();

drop trigger if exists students_set_updated_fields on public.students;
create trigger students_set_updated_fields
before update on public.students
for each row execute function public.set_updated_fields();

drop trigger if exists teacher_tasks_set_updated_fields on public.teacher_tasks;
create trigger teacher_tasks_set_updated_fields
before update on public.teacher_tasks
for each row execute function public.set_updated_fields();

drop trigger if exists attendance_records_set_updated_fields on public.attendance_records;
create trigger attendance_records_set_updated_fields
before update on public.attendance_records
for each row execute function public.set_updated_fields();

drop trigger if exists teacher_profiles_set_updated_fields on public.teacher_profiles;
create trigger teacher_profiles_set_updated_fields
before update on public.teacher_profiles
for each row execute function public.set_updated_fields();

-- ---------------------------------------------------------------------------
-- Storage bucket for syllabi PDFs
-- Run this in Supabase SQL Editor or Dashboard → Storage
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('syllabi', 'syllabi', true)
on conflict (id) do nothing;

drop policy if exists "syllabi_upload_authenticated" on storage.objects;
create policy "syllabi_upload_authenticated"
on storage.objects for insert
to authenticated
with check (bucket_id = 'syllabi' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "syllabi_select_public" on storage.objects;
create policy "syllabi_select_public"
on storage.objects for select
to public
using (bucket_id = 'syllabi');

drop policy if exists "syllabi_delete_own" on storage.objects;
create policy "syllabi_delete_own"
on storage.objects for delete
to authenticated
using (bucket_id = 'syllabi' and (storage.foldername(name))[1] = auth.uid()::text);

-- Optional helper view for moderator dashboard
create or replace view public.attendance_summary_by_teacher as
select
    ar.teacher_id,
    coalesce(tp.full_name, u.email) as teacher_name,
    count(*) filter (where ar.status = 'present') as present_count,
    count(*) filter (where ar.status = 'absent') as absent_count,
    count(*) filter (where ar.status = 'late') as late_count
from public.attendance_records ar
left join public.teacher_profiles tp on tp.user_id = ar.teacher_id
left join auth.users u on u.id = ar.teacher_id
group by ar.teacher_id, teacher_name;
